<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

https://www.wandb.com/articles/fundamentals-of-neural-networks

https://ml-cheatsheet.readthedocs.io/en/latest/nn_concepts.html

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: 
This is the layer which takes input from the dataset. So this layer takes the initial data for the neural network.
### Hidden Layer: 
This is layer which is between input layer and the output layer and also the stage where activation function is applied and then the results are passed on to the next layer. There are often multiple hidden layers in a network.
### Output Layer:
 This is the final layer in the network. Output layer produces the result for given inputs, ie. this layer shows what the actual prediction for the function is.
### Neuron:
The basic unit of computation in a neural network is the neuron
### Weight:
The weight show how important the output for each node plays in determining the output of the function. Wieghts can also be defined as parameters
### Activation Function:
activation function defines if given node should be “activated” or not based on the weighted sum.
### Node Map:
The Node Map is a visual diagram that shows how the neural network works. How the outputs of of node move on to the next node so that you can have an idea of how it works
### Perceptron:
The simplest kind of neural network that only has a single node that can take any number of inputs and spit out an output.
A perceptron follows the “feed-forward” model, meaning inputs are sent into the neuron, are processed, and result in an output


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here
https://natureofcode.com/book/chapter-10-neural-networks/

The information starts out in the dataset and and is put into the input layer of the neural network the network then takes that information and uses an activation function to pass it to the first hidden layer where it is multiplied by the weight and then passed to the next hidden layer until it hits the output layer where it adds the bias and the spits out a human readable prediction.

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [19]:
import pandas as pd
import numpy as np
np.random.seed(812)
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')
df.values

array([[0, 0, 1],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 0]])

In [20]:
##### Your Code Here #####
# define the sigmoid and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1 - sx)


In [21]:
# Initialize the random weights for the inputs
weights = 2 * np.random.random((2,1)) - 1
weights

array([[0.0099616 ],
       [0.21185521]])

In [22]:
# separate the inputs from the output
inputs = df[["x1","x2"]]
correct_out = [[1],[1],[1],[0]]

In [23]:
# create a for loop to update our weights 1,000 times
for iteration in range(1000):
    # weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights) + 7
    # activate
    activated_output = sigmoid(weighted_sum)
    # calculate error
    error = correct_out - activated_output
    adjustments = error * sigmoid_derivative(weighted_sum)
    # Update the weights
    weights += np.dot(inputs.T, adjustments)
#     breakpoint()
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[-4.66977654]
 [-4.66353102]]
Output after training
[[0.99908895]
 [0.91134627]
 [0.91185586]
 [0.08840182]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [24]:
import pandas as pd
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
print(diabetes.shape)
diabetes.head()

(768, 9)


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [25]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

X = diabetes[feats]
y = diabetes['Outcome']
transformer = Normalizer().fit(X)
X = pd.DataFrame(transformer.transform(X))
X.columns = feats
print(X.shape)
X.head()

(768, 8)


Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0     0.033552  0.827625       0.402628       0.195722  0.000000  0.187893   
1     0.008424  0.716040       0.555984       0.244296  0.000000  0.224079   
2     0.040398  0.924097       0.323181       0.000000  0.000000  0.117658   
3     0.006612  0.588467       0.436392       0.152076  0.621527  0.185797   
4     0.000000  0.596386       0.174127       0.152361  0.731335  0.187622   

   DiabetesPedigreeFunction       Age  
0                  0.003506  0.279603  
1                  0.002957  0.261144  
2                  0.003393  0.161591  
3                  0.001104  0.138852  
4                  0.009960  0.143655

In [26]:
import numpy as np
y = np.array(y).reshape(768,1)

In [27]:
##### Update this Class #####
#https://towardsdatascience.com/perceptron-explanation-implementation-and-a-visual-example-3c8e76b4e2d1

class Perceptron:
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        sx = sigmoid(x)
        return sx * (1 - sx)

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """
        
        # Randomly Initialize Weights
        weights = 2 * np.random.random((len(X.columns),1)) - 1

        for i in range(self.niter):
            # Weighted sum of inputs / weights
            weighted_sum = np.dot(X, weights) + 10.969
            # Activate!
            activated_output = sigmoid(weighted_sum)
            # Cac error
            error = y - activated_output
            adjustments = error * sigmoid_derivative(weighted_sum)
            # Update the Weights
            weights += np.dot(X.T, adjustments)
            
        self.weights = weights
        self.activated_output = activated_output



    def predict(self, X):
        """Return class label after unit step"""
        print(self.activated_output)

In [29]:
perceptron = Perceptron(200)
perceptron.fit(X,y)
perceptron.predict(X)

[[0.99998385]
 [0.99998372]
 [0.99998483]
 [0.99996998]
 [0.99996349]
 [0.99998579]
 [0.99996779]
 [0.99998297]
 [0.99995879]
 [0.99998771]
 [0.99998577]
 [0.99998496]
 [0.99998658]
 [0.9999575 ]
 [0.99997007]
 [0.9999833 ]
 [0.99996172]
 [0.99998597]
 [0.99996757]
 [0.99997161]
 [0.9999627 ]
 [0.99998683]
 [0.99998499]
 [0.99998384]
 [0.99997189]
 [0.99997216]
 [0.99998539]
 [0.999967  ]
 [0.99997615]
 [0.99998613]
 [0.99998512]
 [0.99996339]
 [0.99997641]
 [0.99998686]
 [0.99998477]
 [0.99996311]
 [0.99998568]
 [0.99998436]
 [0.99998199]
 [0.99996412]
 [0.99997646]
 [0.99998555]
 [0.99998621]
 [0.99996821]
 [0.99998523]
 [0.99998176]
 [0.99998439]
 [0.99998369]
 [0.99998319]
 [0.99998439]
 [0.99997514]
 [0.99997867]
 [0.99998164]
 [0.99996478]
 [0.99996027]
 [0.99998447]
 [0.99996259]
 [0.99996829]
 [0.99998519]
 [0.99996391]
 [0.99998413]
 [0.99998566]
 [0.99998763]
 [0.99996839]
 [0.99998592]
 [0.99998426]
 [0.99998419]
 [0.99998631]
 [0.99997976]
 [0.99997395]
 [0.99997191]
 [0.99

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?